name: 'primer_impacto'
version: '1.0.0'
config-version: 2

profile: 'primer_impacto'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  primer_impacto:
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
