name: 'data_analyst_test'
version: '1.0.0'
config-version: 2

profile: 'data_analyst_test'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  data_analyst_test:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
